### ISSUE TITLE
Add -frust-very-long flag to CI

### ISSUE THREAD

**Issue by CohenArthur** [Rust-GCC/cargo-gccrs#68]
Otherwise this causes the CI to consistently fail.

**Comment by Taym95** [comment]
Hi, can you point me where CI config are, I can pick it up, thanks

**Comment by bjorn3** [comment]
https://github.com/Rust-GCC/cargo-gccrs/blob/main/.github/workflows/fmt_build_tests.yml

**Comment by CohenArthur** [comment]
@Taym95 the actual flag isn't -frust-very-long, I thought I'd be the one taking care of this :) you an look at the CI failure on your PR to see what it should look like exactly. It should be 

`-frust-incomplete-and-experimental-compiler-do-not-use`

And I believe you might need to change some code in cargo-gccrs as well to handle `GCCRS_EXTRA_FLAGS` as an environment variable instead of `GCC_EXTRA_FLAGS`. I can't remember exactly where that happens but can point it to you soon

**Comment by Taym95** [comment]
@CohenArthur  Ah okay you can take care of it, I will keep eye on your implementation to learn from it!
